### ISSUE TITLE
Item Popularity measure

### ISSUE THREAD

**Issue by JasonTam** [maciejkula/mixture#4]
Hi there, for the calculation of the 95/50 percentile ratio for item popularity, shouldn't you be summing number interactions over the other axis?

https://github.com/maciejkula/mixture/blob/138d8f47a28bc92bd846643330dbdf67f50e6e61/mixture/results.py#L281

Currently, with `axis=1`, we get the number of interactions per user, but I think we want `axis=0` to get interactions per item (?)

Also, I was wondering if this measure was inspired by any specific source. I've never seen it and it seems cool! (btw, great paper as always a pleasure to read :) )

**Comment by maciejkula** [comment]
This is absolutely correct: thank you for the correction! Fix in https://github.com/maciejkula/mixture/pull/5

No wonder most people don't release experimental code :)
